### ISSUE TITLE
[Feature] Probationary period tracking

### ISSUE THREAD

**Issue by James1x0** [associatedemployers/igneous#198]
- [x] Add `probationaryPeriod` field to company model
- [x] Add `probationUntil` field to employee model
- [x] Add recomputing middleware to employee#pre(save) to recalculate `probationUntil` based on `hireDate` and `probationaryPeriod`
